Alexs Branch
USFCEN4020/CEN4020F21TeamWyoming pull request #22
Opened 2021-10-12 17:48 UTC by alogorzusf

**What was added**

1.  added a 'friends' field to accounts which is just an empty array
2.  increased account limit to 10
3.  added feature to search for a student based on major, lastname or uni

Notes: the user_loop was just commented out so that i could isolate and test the new feature, which seems to work fine.

2021-10-13 12:38 UTC, alisnichenko requested changes
Good push! I would suggest to rename the commit message from "Alexs Branch" to something like "Add search student functionality"

2021-10-13 12:38 UTC, alisnichenko commented on src/utils.py
> +        valid_keys = ["lastname", "major", "university"]
I feel like that should be stored in the config, since we might need to modify it later. What do you think?

2021-10-13 12:38 UTC, alisnichenko commented on src/utils.py
> +            return -1
You don't have to return a value in Python. If you really want to have a `return` statement, you can `return None` instead, and on the accepting end, you check `if response: ...` which is equal to `if response is not None: ...`.

2021-10-13 12:38 UTC, alisnichenko commented on src/utils.py
> +                if account[key] == value:
Dictionaries are hashmaps, therefore, you can just look up `accounts[key]` without a for-loop

2021-10-13 12:38 UTC, alisnichenko commented on src/utils.py
> +        num_users_flag = len(self.config['accounts']) >= 10
Oh, you've already satisfied the requirement. Nice! I think it should be `>` though.

2021-10-13 12:38 UTC, alisnichenko commented on src/in_college.py
> +    print(config.search_student('lastame', 'admin'))
Is that supposed to be here?

2021-10-14 18:46 UTC, alogorzusf commented on src/utils.py
> +        valid_keys = ["lastname", "major", "university"]
hmm dont think its super necessary... But if you'd like to do that its fine

2021-10-14 18:50 UTC, alogorzusf commented on src/utils.py
> +                if account[key] == value:
i need the loop to iterate over all of the accounts not just one

2021-10-14 19:02 UTC, closed without merging